// Auth

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const EMAIL_RESEND = 'EMAIL_RESEND';
export const AUTH_ERROR = 'AUTH_ERROR';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';
export const CODE_ERROR = 'CODE_ERROR';
export const HANDLER_ADDED = 'HANDLER_ADDED';
export const HANDLER_ERROR = 'HANDLER_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LINK_SENT = 'LINK_SENT';
export const TOKEN_CONFIRMED = 'TOKEN_CONFIRMED';
export const RESET_PASS_SUCCESSS = 'RESET_PASS_SUCCESSS';

//USER

export const USER_LOADED = 'USER_LOADED';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const AVATAR_UPLOADED = 'AVATAR_UPLOADED';
export const AVATAR_FAIL = 'AVATAR_FAIL';
export const UPDATE_BIO = 'UPDATE_BIO';
export const BIO_FAIL = 'BIO_FAIL';
export const SET_PUSHER = 'SET_PUSHER';
export const INFO_UPDATED = 'INFO_UPDATED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const SET_SETTINGS_LOADING = 'SET_SETTINGS_LOADING';
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';

//Profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const NO_PROFILE = 'NO_PROFILE';
export const GET_CHALLENGERS = 'GET_CHALLENGERS';
export const CHALLENGERS_LOADING = 'CHALLENGERS_LOADING';
export const SET_PICK_LOADING = 'SET_PICK_LOADING';
export const PICK_MODIFIED = 'PICK_MODIFIED';
export const OPEN_CHALLENGERS_MODAL = 'OPEN_CHALLENGERS_MODAL';
export const CLOSE_CHALLENGERS_MODAL = 'CLOSE_CHALLENGERS_MODAL';
export const SET_READY_LOADING = 'SET_READY_LOADING';
export const GET_LIKERS = 'GET_LIKERS';

//DEBATES

export const DEBATE_ADDED = 'DEBATE_ADDED';
export const DEBATE_ERROR = 'DEBATE_ERROR';
export const SET_DEBATE_LOADING = 'SET_DEBATE_LOADING';
export const OPEN_CREATE_DEBATE = 'OPEN_CREATE_DEBATE';
export const CLOSE_CREATE_DEBATE = 'CLOSE_CREATE_DEBATE';
export const GET_NEW_DEBATES = 'GET_NEW_DEBATES';
export const CHALLENGE_WITHDRAW = 'CHALLENGE_WITHDRAW';
export const SET_CHALLENGE_LOADING = 'SET_CHALLENGE_LOADING';
export const SET_LIKE_LOADING = 'SET_LIKE_LOADING';
export const LIKE_MODIFIED = 'LIKE_MODIFIED';
export const DEBATE_READY = 'DEBATE_READY';
export const GET_READY_DEBATES = 'GET_READY_DEBATES';
export const GET_MY_DEBATES = 'GET_MY_DEBATES';
export const GET_PROFILE_DEBATES = 'GET_PROFILE_DEBATES';
export const GET_SINGLE_DEBATE = 'GET_SINGLE_DEBATE';
export const DEBATE_JOINED = 'DEBATE_JOINED';
export const GET_LIVE_DEBATES = 'GET_LIVE_DEBATES';
export const SET_ENDED = 'SET_ENDED'; //Only to set title
export const DEBATE_ENDED = 'DEBATE_ENDED';
export const GET_ENDED_DEBATES = 'GET_ENDED_DEBATES';

// Comment

export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const PUSH_COMMENTS = 'PUSH_COMMENTS';
export const SET_COMMENT_LOADING = 'SET_COMMENT_LOADING';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const PULL_COMMENTS = 'PULL_COMMENTS';
